FROM mcr.microsoft.com/playwright/python:v1.51.0-noble

# Copy files to container and set working dir
COPY . /atoti
WORKDIR /atoti

# Install system dependencies
RUN apt-get update \
 && apt-get install -y \
      xvfb \
      git \
      git-lfs \
      debian-archive-keyring \
      build-essential \
      ca-certificates \
 && rm -rf /var/lib/apt/lists/*

# Install dependencies in container (uv style)
RUN pip install uv && \
    uv sync

# Set container executable
CMD [ "make", "render" ]