# receivers
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

# processors
processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

# exporters
exporters:
  otlp:
    endpoint: tempo:7777
    tls:
      insecure: true
  prometheus:
    endpoint: collector:6666
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  debug:
    verbosity: detailed # this is useful for troubleshooting, change it to "normal" once issues fixed

# service
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      exporters: [loki]

# the collector itself can be configured , see https://opentelemetry.io/docs/collector/configuration/    
  telemetry:
    logs:
      level: info

# exporters: [loki, logging] => add logging in case you want more details
