import atoti as tt

nasdaq_100 = [
    "ABNB",
    "ALGN",
    "AMD",
    "CEG",
    "AMZN",
    "AMGN",
    "AEP",
    "ADI",
    "ANSS",
    "AAPL",
    "AMAT",
    "GEHC",
    "ASML",
    "TEAM",
    "ADSK",
    "ATVI",
    "ADP",
    "AZN",
    "BKR",
    "AVGO",
    "BKNG",
    "CDNS",
    "ADBE",
    "CHTR",
    "CPRT",
    "CSGP",
    "CRWD",
    "CTAS",
    "CSCO",
    "CMCSA",
    "COST",
    "CSX",
    "CTSH",
    "DDOG",
    "DXCM",
    "FANG",
    "DLTR",
    "EA",
    "EBAY",
    "ENPH",
    "ON",
    "EXC",
    "FAST",
    "GFS",
    "META",
    "FI",
    "FTNT",
    "GILD",
    "GOOG",
    "GOOGL",
    "HON",
    "ILMN",
    "INTC",
    "INTU",
    "ISRG",
    "MRVL",
    "IDXX",
    "JD",
    "KDP",
    "KLAC",
    "KHC",
    "LRCX",
    "LCID",
    "LULU",
    "MELI",
    "MAR",
    "MCHP",
    "MDLZ",
    "MRNA",
    "MNST",
    "MSFT",
    "MU",
    "NFLX",
    "NVDA",
    "NXPI",
    "ODFL",
    "ORLY",
    "PCAR",
    "PANW",
    "PAYX",
    "PDD",
    "PYPL",
    "PEP",
    "QCOM",
    "REGN",
    "ROST",
    "SIRI",
    "SGEN",
    "SBUX",
    "SNPS",
    "TSLA",
    "TXN",
    "TMUS",
    "VRSK",
    "VRTX",
    "WBA",
    "WBD",
    "WDAY",
    "XEL",
    "ZM",
    "ZS",
]

"""
The below are all of the columns available in the ESG data set from GSQ. For the sake of this demo, we've focused on key personnel departures in the past year. To utilize other datasets (and rename them) comment and uncomment as desired.
"""

esg_cols = {
    "Delivery_Date": "report_date",
    "symbol": "symbol",
    # "111" : "Share_of_non-audit_fees_to_total_fees_paid_to_the_auditor_during_last_reported_fiscal_period",
    # "112" : "Auditor_opinion_for_last_reported_fiscal_period",
    "1131y": "#auditor_departures_of_in_past_1_year",
    # "1132y" : "#auditor_departures_of_in_past_2_year",
    # "1133y" : "#auditor_departures_of_in_past_3_years",
    # "1134y" : "#auditor_departures_of_in_past_4_years",
    # "1135y" : "#auditor_departures_of_in_past_5_years",
    # "114" : "Current_Auditor_-_if_top-tier_(big_four)",
    # "1211y" : "#restatements_in_past_1_years",
    # "1212y" : "#restatements_in_past_2_years",
    # "1213y" : "#restatements_in_past_3_years",
    # "1214y" : "#restatements_in_past_4_years",
    # "1215y" : "#restatements_in_past_5_years",
    # "1216m" : "#restatements_in_past_6_months",
    # "1221y" : "#fiscal_quarters_non-recurring_items_exceed_5%_of_sales_or_1.5%_of_net_assets_in_past_4_quarters",
    # "1222y" : "#fiscal_quarters_non-recurring_items_exceed_5%_of_sales_or_1.5%_of_net_assets_in_past_8_quarters",
    # "1223y" : "#fiscal_quarters_non-recurring_items_exceed_5%_of_sales_or_1.5%_of_net_assets_in_past_12_quarters",
    # "1224y" : "#fiscal_quarters_non-recurring_items_exceed_5%_of_sales_or_1.5%_of_net_assets_in_past_16_quarters",
    # "1225y" : "#fiscal_quarters_non-recurring_items_exceed_5%_of_sales_or_1.5%_of_net_assets_in_past_20_quarters",
    # "1226m" : "#fiscal_quarters_non-recurring_items_exceed_5%_of_sales_or_1.5%_of_net_assets_in_past_2_quarters",
    # "1231y" : "#times_earnings_est_lowered_in_past_1_year",
    # "1232y" : "#times_earnings_est_lowered_in_past_2_years",
    # "1233y" : "#times_earnings_est_lowered_in_past_3_years",
    # "1234y" : "#times_earnings_est_lowered_in_past_4_years",
    # "1235y" : "#times_earnings_est_lowered_in_past_5_years",
    # "1236m" : "#times_earnings_est_lowered_in_past_6_months",
    # "1241y" : "#delayed_filings_in_past_1_years",
    # "1242y" : "#delayed_filings_in_past_2_years",
    # "1243y" : "#delayed_filings_in_past_3_years",
    # "1244y" : "#delayed_filings_in_past_4_years",
    # "1245y" : "#delayed_filings_in_past_5_years",
    # "1246m" : "#delayed_filings_in_past_6_months",
    # "1247" : "#delayed_filings_remaining_delinquent",
    # "12471" : "#delayed_filings_remaining_delinquent_for_more_than_1_month",
    # "12471y" : "#delayed_filing_delinquency_lasted_for_more_than_1_month_in_past_1_year",
    # "12472y" : "#delayed_filing_delinquency_lasted_for_more_than_1_month_in_past_2_years",
    # "12473y" : "#delayed_filing_delinquency_lasted_for_more_than_1_month_in_past_3_years",
    # "12474y" : "#delayed_filing_delinquency_lasted_for_more_than_1_month_in_past_4_years",
    # "12475y" : "#delayed_filing_delinquency_lasted_for_more_than_1_month_in_past_5_years",
    # "12476m" : "#delayed_filing_delinquency_lasted_for_more_than_1_month_in_past_6_months",
    # "1251y" : "#times_material_control_weakness_identified_in_past_1_years",
    # "1252y" : "#times_material_control_weakness_identified_in_past_2_years",
    # "1253y" : "#times_material_control_weakness_identified_in_past_3_years",
    # "1254y" : "#times_material_control_weakness_identified_in_past_4_years",
    # "1255y" : "#times_material_control_weakness_identified_in_past_5_years",
    # "126" : "Material_control_weakness_currently_remaining_unremediated",
    # "1311y" : "#SEC_investigations_initially_disclosed_in_past_1_year",
    # "1312y" : "#SEC_investigations_initially_disclosed_in_past_2_year",
    # "1313y" : "#SEC_investigations_initially_disclosed_in_past_3_year",
    # "1314y" : "#SEC_investigations_initially_disclosed_in_past_4_year",
    # "1315y" : "#SEC_investigations_initially_disclosed_in_past_5_year",
    # "1316m" : "#SEC_investigations_initially_disclosed_in_past_6_months",
    # "132" : "#SEC_investigations_currently_remaining_open",
    # "1331y" : "#enforcement_actions_by_the_SEC_(Wells_Notice)_in_past_1_years",
    # "1332y" : "#enforcement_actions_by_the_SEC_(Wells_Notice)_in_past_2_years",
    # "1333y" : "#enforcement_actions_by_the_SEC_(Wells_Notice)_in_past_3_years",
    # "1334y" : "#enforcement_actions_by_the_SEC_(Wells_Notice)_in_past_4_years",
    # "1335y" : "#enforcement_actions_by_the_SEC_(Wells_Notice)_in_past_5_years",
    # "1336m" : "#enforcement_actions_by_the_SEC_(Wells_Notice)_in_past_6_months",
    # "1341y" : "#DoJ_or_State_AG_investigations_in_past_1_years",
    # "1342y" : "#DoJ_or_State_AG_investigations_in_past_2_years",
    # "1343y" : "#DoJ_or_State_AG_investigations_in_past_3_years",
    # "1344y" : "#DoJ_or_State_AG_investigations_in_past_4_years",
    # "1345y" : "#DoJ_or_State_AG_investigations_in_past_5_years",
    # "1346m" : "#DoJ_or_State_AG_investigations_in_past_6_Months",
    # "135" : "#DoJ_or_State_AG_investigations_currently_remaining_open",
    # "1361y" : "#Audit_Committee_investigations_in_past_1_years",
    # "1362y" : "#Audit_Committee_investigations_in_past_2_years",
    # "1363y" : "#Audit_Committee_investigations_in_past_3_years",
    # "1364y" : "#Audit_Committee_investigations_in_past_4_years",
    # "1365y" : "#Audit_Committee_investigations_in_past_5_years",
    # "1366m" : "#Audit_Committee_investigations_in_past_6MO",
    # "137" : "#Audit_Committee_investigations_currently_remaining_open",
    # "1381y" : "#SEC_staff_reviews_in_past_1_year",
    # "1382y" : "#SEC_staff_reviews_in_past_2_year",
    # "1383y" : "#SEC_staff_reviews_in_past_3_year",
    # "1384y" : "#SEC_staff_reviews_in_past_4_year",
    # "1385y" : "#SEC_staff_reviews_in_past_5_year",
    # "1386m" : "#SEC_staff_reviews_in_past_6_MO",
    # "1391y" : "#SEC_staff_reviews_which_lasted_for_more_than_6_months_in_past_1_year",
    # "1392y" : "#SEC_staff_reviews_which_lasted_for_more_than_6_months_in_past_2_years",
    # "1393y" : "#SEC_staff_reviews_which_lasted_for_more_than_6_months_in_past_3_years",
    # "1394y" : "#SEC_staff_reviews_which_lasted_for_more_than_6_months_in_past_4_years",
    # "1395y" : "#SEC_staff_reviews_which_lasted_for_more_than_6_months_in_past_5_years",
    # "1310" : "#SEC_staff_reviews_currently_remaining_open",
    # "1311" : "#SEC_staff_reviews_currently_remaining_open_for_more_than_6_months",
    # "13121y" : "#SEC_staff_reviews_raising_revenue_recognition_issue_in_past_1_year",
    # "13122y" : "#SEC_staff_reviews_raising_revenue_recognition_issue_in_past_2_years",
    # "13123y" : "#SEC_staff_reviews_raising_revenue_recognition_issue_in_past_3_years",
    # "13124y" : "#SEC_staff_reviews_raising_revenue_recognition_issue_in_past_4_years",
    # "13125y" : "#SEC_staff_reviews_raising_revenue_recognition_issue_in_past_5_years",
    # "13126m" : "#SEC_staff_reviews_raising_revenue_recognition_issue_in_past_6_months",
    # "13131y" : "#SEC_staff_reviews_raising_expense_recognition_issue_in_past_1_year",
    # "13132y" : "#SEC_staff_reviews_raising_expense_recognition_issue_in_past_2_years",
    # "13133y" : "#SEC_staff_reviews_raising_expense_recognition_issue_in_past_3_years",
    # "13134y" : "#SEC_staff_reviews_raising_expense_recognition_issue_in_past_4_years",
    # "13135y" : "#SEC_staff_reviews_raising_expense_recognition_issue_in_past_5_years",
    # "13136m" : "#SEC_staff_reviews_raising_expense_recognition_issue_in_past_6_months",
    # "13141y" : "#SEC_staff_reviews_raising_issues_related_to_reserves_in_past_1_year",
    # "13142y" : "#SEC_staff_reviews_raising_issues_related_to_reserves_in_past_2_years",
    # "13143y" : "#SEC_staff_reviews_raising_issues_related_to_reserves_in_past_3_years",
    # "13144y" : "#SEC_staff_reviews_raising_issues_related_to_reserves_in_past_4_years",
    # "13145y" : "#SEC_staff_reviews_raising_issues_related_to_reserves_in_past_5_years",
    # "13146m" : "#SEC_staff_reviews_raising_issues_related_to_reserves_in_past_6_months",
    # "13151y" : "#SEC_staff_reviews_raising_issues_pertaining_to_Related_Party_Transactions_in_past_1_year",
    # "13152y" : "#SEC_staff_reviews_raising_issues_pertaining_to_Related_Party_Transactions_in_past_2_years",
    # "13153y" : "#SEC_staff_reviews_raising_issues_pertaining_to_Related_Party_Transactions_in_past_3_years",
    # "13154y" : "#SEC_staff_reviews_raising_issues_pertaining_to_Related_Party_Transactions_in_past_4_years",
    # "13155y" : "#SEC_staff_reviews_raising_issues_pertaining_to_Related_Party_Transactions_in_past_5_years",
    # "13156m" : "#SEC_staff_reviews_raising_issues_pertaining_to_Related_Party_Transactions_in_past_6_months",
    # "13161y" : "#SEC_staff_reviews_raising_issues_pertaining_to_asset_carrying_value,_impairment_or_write_down_in_past_1_year",
    # "13162y" : "#SEC_staff_reviews_raising_issues_pertaining_to_asset_carrying_value,_impairment_or_write_down_in_past_2_years",
    # "13163y" : "#SEC_staff_reviews_raising_issues_pertaining_to_asset_carrying_value,_impairment_or_write_down_in_past_3_years",
    # "13164y" : "#SEC_staff_reviews_raising_issues_pertaining_to_asset_carrying_value,_impairment_or_write_down_in_past_4_years",
    # "13165y" : "#SEC_staff_reviews_raising_issues_pertaining_to_asset_carrying_value,_impairment_or_write_down_in_past_5_years",
    # "13166m" : "#SEC_staff_reviews_raising_issues_pertaining_to_asset_carrying_value,_impairment_or_write_down_in_past_6_months",
    # "13171y" : "#SEC_staff_reviews_raising_issues_pertaining_to_executive_compensation_in_past_1_year",
    # "13172y" : "#SEC_staff_reviews_raising_issues_pertaining_to_executive_compensation_in_past_2_years",
    # "13173y" : "#SEC_staff_reviews_raising_issues_pertaining_to_executive_compensation_in_past_3_years",
    # "13174y" : "#SEC_staff_reviews_raising_issues_pertaining_to_executive_compensation_in_past_4_years",
    # "13175y" : "#SEC_staff_reviews_raising_issues_pertaining_to_executive_compensation_in_past_5_years",
    # "13176m" : "#SEC_staff_reviews_raising_issues_pertaining_to_executive_compensation_in_past_6_months",
    # "211" : "Each_common_equity_share_has_the_same_#votes_and_without_encumbrance",
    # "212" : "Voting_policy_and_director_resignation_policy_in_uncontested_elections",
    # "213" : "Supermajority_required_to_amend_charter_and_bylaws",
    # "214" : "Supermajority_required_to_approve_M&A_activities",
    # "221" : "Staggered_board",
    # "2221" : "Shareholder_rights_plan_approved_by_shareholders",
    # "2222" : "Shareholder_rights_plan_trigger:_ownership_percentage",
    # "2223" : "Shareholder_rights_plan_has_qualified_offer_provision",
    # "2224" : "Shareholder_Rights_Plan_-_Expiry_in_years",
    # "2225" : "Shareholder_rights_plan_-_since_effectuated_or_last_reintroduced_in_years",
    # "223" : "Board_authorized_to_issue_blank_check_preferred_stock_without_shareholders_approval",
    # "231" : "Convening_Special_Meeting_-_Ownership_percentage_requirement",
    # "232" : "Shareholders_can_act_through_written_consent",
    # "2411y" : "#times_listing_standards_were_violated_or_notice_of_delisting_served_in_past_1_year",
    # "2412y" : "#times_listing_standards_were_violated_or_notice_of_delisting_served_in_past_2_years",
    # "2413y" : "#times_listing_standards_were_violated_or_notice_of_delisting_served_in_past_3_years",
    # "2414y" : "#times_listing_standards_were_violated_or_notice_of_delisting_served_in_past_4_years",
    # "2415y" : "#times_listing_standards_were_violated_or_notice_of_delisting_served_in_past_5_years",
    # "2416m" : "#times_listing_standards_were_violated_or_notice_of_delisting_served_in_past_6_months",
    # "2421y" : "#instances_of_suspension_of_trading_in_past_1_year",
    # "2422y" : "#instances_of_suspension_of_trading_in_past_2_years",
    # "2423y" : "#instances_of_suspension_of_trading_in_past_3_years",
    # "2424y" : "#instances_of_suspension_of_trading_in_past_4_years",
    # "2425y" : "#instances_of_suspension_of_trading_in_past_5_years",
    # "2426m" : "#instances_of_suspension_of_trading_in_past_6m",
    # "311" : "CEO_holds_Board_Chair",
    # "312" : "%_independent_directors",
    # "321" : "%_independent_audit_committee_members",
    # "322" : "%_independent_compensation_committee_members",
    # "323" : "%_independent_nominating_committee_members",
    # "331" : "%_directors_on_4_or_more_(other)_public_company_boards_on_last_reported_proxy_record_date",
    # "332" : "#other_public_company_boards_the_CEO_serves_on_last_reported_proxy_record_date",
    # "333" : "%_meetings_directors_attended_in_a_year_>=75%_as_reported_on_last_proxy_statement",
    # "341" : "If_there_are_disclosed_governance_guidelines",
    # "342" : "If_Non-executive_directors_met_without_the_presence_of_executive_members_(executive_sessions)_at_least_once_in_a_year,_as_reported_on_last_proxy_statement",
    # "3441y" : "#related_party_transactions_involving_board_chair_and_or_CEO_in_past_1_year",
    # "3442y" : "#related_party_transactions_involving_board_chair_and_or_CEO_in_past_2_years",
    # "3443y" : "#related_party_transactions_involving_board_chair_and_or_CEO_in_past_3_years",
    # "3444y" : "#related_party_transactions_involving_board_chair_and_or_CEO_in_past_4_years",
    # "3445y" : "#related_party_transactions_involving_board_chair_and_or_CEO_in_past_5_years",
    "3511y": "#board_chair_departures_in_past_1_year",
    # "3512y" : "#board_chair_departures_in_past_2_years",
    # "3513y" : "#board_chair_departures_in_past_3_years",
    # "3514y" : "#board_chair_departures_in_past_4_years",
    # "3515y" : "#board_chair_departures_in_past_5_years",
    # "3516m" : "#board_chair_departures_in_past_6_months",
    "3521y": "#audit_committee_chair_departures_in_past_1_year",
    # "3522y" : "#audit_committee_chair_departures_in_past_2_years",
    # "3523y" : "#audit_committee_chair_departures_in_past_3_years",
    # "3524y" : "#audit_committee_chair_departures_in_past_4_years",
    # "3525y" : "#audit_committee_chair_departures_in_past_5_years",
    # "3526m" : "#audit_committee_chair_departures_in_past_6_months",
    "3531y": "#compensation_committee_chair_departures_in_past_1_year",
    # "3532y" : "#compensation_committee_chair_departures_in_past_2_years",
    # "3533y" : "#compensation_committee_chair_departures_in_past_3_years",
    # "3534y" : "#compensation_committee_chair_departures_in_past_4_years",
    # "3535y" : "#compensation_committee_chair_departures_in_past_5_years",
    # "3536m" : "#compensation_committee_chair_departures_in_past_6_months",
    "3541y": "#nominating_committee_chair_departures_in_past_1_year",
    # "3542y" : "#nominating_committee_chair_departures_in_past_2_years",
    # "3543y" : "#nominating_committee_chair_departures_in_past_3_years",
    # "3544y" : "#nominating_committee_chair_departures_in_past_4_years",
    # "3545y" : "#nominating_committee_chair_departures_in_past_5_years",
    # "3546m" : "#nominating_committee_chair_departures_in_past_6_months",
    "3551y": "#board_departures_in_past_1_year",
    # "3552y" : "#board_departures_in_past_2_years",
    # "3553y" : "#board_departures_in_past_3_years",
    # "3554y" : "#board_departures_in_past_4_years",
    # "3555y" : "#board_departures_in_past_5_years",
    # "3556m" : "#board_departures_in_past_6_months",
    "3561y": "#audit_committee_departures_in_past_1_year",
    # "3562y" : "#audit_committee_departures_in_past_2_years",
    # "3563y" : "#audit_committee_departures_in_past_3_years",
    # "3564y" : "#audit_committee_departures_in_past_4_years",
    # "3565y" : "#audit_committee_departures_in_past_5_years",
    # "3566m" : "#audit_committee_departures_in_past_6_months",
    "3571y": "#compensation_committee_departures_in_past_1_year",
    # "3572y" : "#compensation_committee_departures_in_past_2_years",
    # "3573y" : "#compensation_committee_departures_in_past_3_years",
    # "3574y" : "#compensation_committee_departures_in_past_4_years",
    # "3575y" : "#compensation_committee_departures_in_past_5_years",
    # "3576m" : "#compensation_committee_departures_in_past_6_months",
    "3581y": "#nominating_committee_departures_in_past_1_year",
    # "3582y" : "#nominating_committee_departures_in_past_2_years",
    # "3583y" : "#nominating_committee_departures_in_past_3_years",
    # "3584y" : "#nominating_committee_departures_in_past_4_years",
    # "3585y" : "#nominating_committee_departures_in_past_5_years",
    # "3586m" : "#nominating_committee_departures_in_past_6_months",
    # "41y1" : "Pay_performance_alignment:_1-year_annualized_CEO_compensation_versus_1-year_TSR_(total_shareholder_return)_in_peer_group",
    # "41y2" : "Pay_performance_alignment:_1-year_top_5_NEO_(named_executive_officers)_aggregate_compensation_versus_1-year_TSR_in_peer_group",
    # "41y3" : "Pay_performance_alignment:_1-year_annualized_CEO_compensation_versus_1-year_annual_ROTC_(return_on_total_capital)_in_peer_group",
    # "41y4" : "Pay_performance_alignment:_1-year_top_5_NEO_aggregate_compensation_versus_1-year_annual_ROTC_in_peer_group",
    # "42y1" : "Pay_performance_alignment:_2-year_average_annualized_CEO_compensation_versus_2-year_compounded_annualized_TSR_in_peer_group",
    # "42y2" : "Pay_performance_alignment:_2-year_average_annual_top_5_NEO_aggregate_compensation_versus_2-_year_compounded_annualized_TSR_in_peer_group",
    # "42y3" : "Pay_performance_alignment:_2-year_average_annualized_CEO_compensation_versus_2-year_average_annual_ROTC_in_peer_group",
    # "42y4" : "Pay_performance_alignment:_2-year_average_annual_top_5_NEO_aggregate_compensation_versus_2-year_average_annual_ROTC_in_peer_group",
    # "43y1" : "Pay_performance_alignment:_3-year_average_annualized_CEO_compensation_versus_3-year_compounded_annualized_TSR_in_peer_group",
    # "43y2" : "Pay_performance_alignment:_3-year_average_annual_top_5_NEO_aggregate_compensation_versus_3-year_compounded_annualized_TSR_in_peer_group",
    # "43y3" : "Pay_performance_alignment:_3-year_average_annualized_CEO_compensation_versus_3-year_average_annual_ROTC_in_peer_group",
    # "43y4" : "Pay_performance_alignment:_3-year_average_annual_top_5_NEO_aggregate_compensation_versus_3-year_average_annual_ROTC_in_peer_group",
    # "44y1" : "Pay_performance_alignment:_4-year_average_annualized_CEO_compensation_versus_4-year_compounded_annualized_TSR_in_peer_group",
    # "44y2" : "Pay_performance_alignment:_4-year_average_annual_top_5_NEO_aggregate_compensation_versus_4-year_compounded_annualized_TSR_in_peer_group",
    # "44y3" : "Pay_performance_alignment:_4-year_average_annualized_CEO_compensation_versus_4-year_average_annual_ROTC_in_peer_group",
    # "44y4" : "Pay_performance_alignment:_4-year_average_annual_top_5_NEO_aggregate_compensation_versus_4-year_average_annual_ROTC_in_peer_group",
    # "45y1" : "Pay_performance_alignment:_5-year_average_annualized_CEO_compensation_versus_5-year_compounded_annualized_TSR_in_peer_group",
    # "45y2" : "Pay_performance_alignment:_5-year_average_annual_top_5_NEO_aggregate_compensation_versus_5-year_compounded_annualized_TSR_in_peer_group",
    # "45y3" : "Pay_performance_alignment:_5-year_average_annualized_CEO_compensation_versus_5-year_average_annual_ROTC_in_peer_group",
    # "45y4" : "Pay_performance_alignment:_5-year_average_annual_top_5_NEO_aggregate_compensation_versus_5-year_average_annual_ROTC_in_peer_group",
    # "421" : "If_shareholders_have_Say_on_Pay",
    # "422" : "If_there_is_disclosed_compensation_claw_back_provision",
    "4311y": "#CEO_departures_in_past_1_year",
    # "4312y" : "#CEO_departures_in_past_2_years",
    # "4313y" : "#CEO_departures_in_past_3_years",
    # "4314y" : "#CEO_departures_in_past_4_years",
    # "4315y" : "#CEO_departures_in_past_5_years",
    # "4316m" : "#CEO_departures_in_past_6_months",
    "4321y": "#CFO_departures_in_past_1_year",
    # "4322y" : "#CFO_departures_in_past_2_years",
    # "4323y" : "#CFO_departures_in_past_3_years",
    # "4324y" : "#CFO_departures_in_past_4_years",
    # "4325y" : "#CFO_departures_in_past_5_years",
    # "4326m" : "#CFO_departures_in_past_6_months",
    "4331y": "#CAO_departures_in_past_1_year",
    # "4332y" : "#CAO_departures_in_past_2_years",
    # "4333y" : "#CAO_departures_in_past_3_years",
    # "4334y" : "#CAO_departures_in_past_4_years",
    # "4335y" : "#CAO_departures_in_past_5_years",
    # "4336m" : "#CAO_departures_in_past_6_months",
    "4341y": "#General_Counsel_departures_in_past_1_year",
    # "4342y" : "#General_Counsel_departures_in_past_2_years",
    # "4343y" : "#General_Counsel_departures_in_past_3_years",
    # "4344y" : "#General_Counsel_departures_in_past_4_years",
    # "4345y" : "#General_Counsel_departures_in_past_5_years",
    # "4346m" : "#General_Counsel_departures_in_past_6_months",
    "4351y": "#COO_departures_in_past_1_year",
    # "4352y" : "#COO_departures_in_past_2_years",
    # "4353y" : "#COO_departures_in_past_3_years",
    # "4354y" : "#COO_departures_in_past_4_years",
    # "4355y" : "#COO_departures_in_past_5_years",
    # "4356m" : "#COO_departures_in_past_6_months",
    "4361y": "#CPO_departures_in_past_1_year",
    # "4362y" : "#CPO_departures_in_past_2_years",
    # "4363y" : "#CPO_departures_in_past_3_years",
    # "4364y" : "#CPO_departures_in_past_4_years",
    # "4365y" : "#CPO_departures_in_past_5_years",
    # "4366m" : "#CPO_departures_in_past_6_months",
    # "5111y" : "#EPA_or_other_regulator_environmental_investigations_in_past_1_year",
    # "5112y" : "#EPA_or_other_regulator_environmental_investigations_in_past_2_years",
    # "5113y" : "#EPA_or_other_regulator_environmental_investigations_in_past_3_years",
    # "5114y" : "#EPA_or_other_regulator_environmental_investigations_in_past_4_years",
    # "5115y" : "#EPA_or_other_regulator_environmental_investigations_in_past_5_years",
    # "5116m" : "#EPA_or_other_regulator_environmental_investigations_in_past_6_months",
    # "512" : "#EPA_or_other_regulator_environmental_investigations_currently_remaining_open",
    # "5211y" : "#regulator_or_board_investigations_on_labor_law_violation_at_workplace_including_within_third-party_supply_chain,_in_past_1_year",
    # "5212y" : "#regulator_or_board_investigations_on_labor_law_violation_at_workplace_including_within_third-party_supply_chain,_in_past_2_years",
    # "5213y" : "#regulator_or_board_investigations_on_labor_law_violation_at_workplace_including_within_third-party_supply_chain,_in_past_3_years",
    # "5214y" : "#regulator_or_board_investigations_on_labor_law_violation_at_workplace_including_within_third-party_supply_chain,_in_past_4_years",
    # "5215y" : "#regulator_or_board_investigations_on_labor_law_violation_at_workplace_including_within_third-party_supply_chain,_in_past_5_years",
    # "5216m" : "#regulator_or_board_investigations_on_labor_law_violation_at_workplace_including_within_third-party_supply_chain,_in_past_6_months",
    # "522" : "#regulator_or_board_investigations_on_labor_law_violation_at_workplace_including_within_third-party_supply_chain,_currently_remaining_open",
    # "523" : "Gender_diversity_in_board_-_percentage_of_women",
    # "524" : "Gender_diversity_in_executive_suite_-_percentage_of_women",
    # "531" : "GRI_(Global_Reporting_Initiative)_reporting:_Application_level",
    # "532" : "GRI_reporting_-_#sustainability_guidelines_referenced",
}

esg_col_types = {
    "report_date": tt.LOCAL_DATE,
    "symbol": tt.STRING,
    # "Share_of_non-audit_fees_to_total_fees_paid_to_the_auditor_during_last_reported_fiscal_period" : tt.FLOAT,
    # "Auditor_opinion_for_last_reported_fiscal_period" : tt.STRING,
    "#auditor_departures_of_in_past_1_year": tt.INT,
    # "#auditor_departures_of_in_past_2_year" : tt.INT,
    # "#auditor_departures_of_in_past_3_years" : tt.INT,
    # "#auditor_departures_of_in_past_4_years" : tt.INT,
    # "#auditor_departures_of_in_past_5_years" : tt.INT,
    # "Current_Auditor_-_if_top-tier_(big_four)" : tt.STRING,
    # "#restatements_in_past_1_years" : tt.INT,
    # "#restatements_in_past_2_years" : tt.INT,
    # "#restatements_in_past_3_years" : tt.INT,
    # "#restatements_in_past_4_years" : tt.INT,
    # "#restatements_in_past_5_years" : tt.INT,
    # "#restatements_in_past_6_months" : tt.INT,
    # "#fiscal_quarters_non-recurring_items_exceed_5%_of_sales_or_1.5%_of_net_assets_in_past_4_quarters" : tt.INT,
    # "#fiscal_quarters_non-recurring_items_exceed_5%_of_sales_or_1.5%_of_net_assets_in_past_8_quarters" : tt.INT,
    # "#fiscal_quarters_non-recurring_items_exceed_5%_of_sales_or_1.5%_of_net_assets_in_past_12_quarters" : tt.INT,
    # "#fiscal_quarters_non-recurring_items_exceed_5%_of_sales_or_1.5%_of_net_assets_in_past_16_quarters" : tt.INT,
    # "#fiscal_quarters_non-recurring_items_exceed_5%_of_sales_or_1.5%_of_net_assets_in_past_20_quarters" : tt.INT,
    # "#fiscal_quarters_non-recurring_items_exceed_5%_of_sales_or_1.5%_of_net_assets_in_past_2_quarters" : tt.INT,
    # "#times_earnings_est_lowered_in_past_1_year" : tt.INT,
    # "#times_earnings_est_lowered_in_past_2_years" : tt.INT,
    # "#times_earnings_est_lowered_in_past_3_years" : tt.INT,
    # "#times_earnings_est_lowered_in_past_4_years" : tt.INT,
    # "#times_earnings_est_lowered_in_past_5_years" : tt.INT,
    # "#times_earnings_est_lowered_in_past_6_months" : tt.INT,
    # "#delayed_filings_in_past_1_years" : tt.INT,
    # "#delayed_filings_in_past_2_years" : tt.INT,
    # "#delayed_filings_in_past_3_years" : tt.INT,
    # "#delayed_filings_in_past_4_years" : tt.INT,
    # "#delayed_filings_in_past_5_years" : tt.INT,
    # "#delayed_filings_in_past_6_months" : tt.INT,
    # "#delayed_filings_remaining_delinquent" : tt.INT,
    # "#delayed_filings_remaining_delinquent_for_more_than_1_month" : tt.INT,
    # "#delayed_filing_delinquency_lasted_for_more_than_1_month_in_past_1_year" : tt.INT,
    # "#delayed_filing_delinquency_lasted_for_more_than_1_month_in_past_2_years" : tt.INT,
    # "#delayed_filing_delinquency_lasted_for_more_than_1_month_in_past_3_years" : tt.INT,
    # "#delayed_filing_delinquency_lasted_for_more_than_1_month_in_past_4_years" : tt.INT,
    # "#delayed_filing_delinquency_lasted_for_more_than_1_month_in_past_5_years" : tt.INT,
    # "#delayed_filing_delinquency_lasted_for_more_than_1_month_in_past_6_months" : tt.INT,
    # "#times_material_control_weakness_identified_in_past_1_years" : tt.INT,
    # "#times_material_control_weakness_identified_in_past_2_years" : tt.INT,
    # "#times_material_control_weakness_identified_in_past_3_years" : tt.INT,
    # "#times_material_control_weakness_identified_in_past_4_years" : tt.INT,
    # "#times_material_control_weakness_identified_in_past_5_years" : tt.INT,
    # "Material_control_weakness_currently_remaining_unremediated" : tt.STRING,
    # "#SEC_investigations_initially_disclosed_in_past_1_year" : tt.INT,
    # "#SEC_investigations_initially_disclosed_in_past_2_year" : tt.INT,
    # "#SEC_investigations_initially_disclosed_in_past_3_year" : tt.INT,
    # "#SEC_investigations_initially_disclosed_in_past_4_year" : tt.INT,
    # "#SEC_investigations_initially_disclosed_in_past_5_year" : tt.INT,
    # "#SEC_investigations_initially_disclosed_in_past_6_months" : tt.INT,
    # "#SEC_investigations_currently_remaining_open" : tt.INT,
    # "#enforcement_actions_by_the_SEC_(Wells_Notice)_in_past_1_years" : tt.INT,
    # "#enforcement_actions_by_the_SEC_(Wells_Notice)_in_past_2_years" : tt.INT,
    # "#enforcement_actions_by_the_SEC_(Wells_Notice)_in_past_3_years" : tt.INT,
    # "#enforcement_actions_by_the_SEC_(Wells_Notice)_in_past_4_years" : tt.INT,
    # "#enforcement_actions_by_the_SEC_(Wells_Notice)_in_past_5_years" : tt.INT,
    # "#enforcement_actions_by_the_SEC_(Wells_Notice)_in_past_6_months" : tt.INT,
    # "#DoJ_or_State_AG_investigations_in_past_1_years" : tt.INT,
    # "#DoJ_or_State_AG_investigations_in_past_2_years" : tt.INT,
    # "#DoJ_or_State_AG_investigations_in_past_3_years" : tt.INT,
    # "#DoJ_or_State_AG_investigations_in_past_4_years" : tt.INT,
    # "#DoJ_or_State_AG_investigations_in_past_5_years" : tt.INT,
    # "#DoJ_or_State_AG_investigations_in_past_6_Months" : tt.INT,
    # "#DoJ_or_State_AG_investigations_currently_remaining_open" : tt.INT,
    # "#Audit_Committee_investigations_in_past_1_years" : tt.INT,
    # "#Audit_Committee_investigations_in_past_2_years" : tt.INT,
    # "#Audit_Committee_investigations_in_past_3_years" : tt.INT,
    # "#Audit_Committee_investigations_in_past_4_years" : tt.INT,
    # "#Audit_Committee_investigations_in_past_5_years" : tt.INT,
    # "#Audit_Committee_investigations_in_past_6MO" : tt.INT,
    # "#Audit_Committee_investigations_currently_remaining_open" : tt.INT,
    # "#SEC_staff_reviews_in_past_1_year" : tt.INT,
    # "#SEC_staff_reviews_in_past_2_year" : tt.INT,
    # "#SEC_staff_reviews_in_past_3_year" : tt.INT,
    # "#SEC_staff_reviews_in_past_4_year" : tt.INT,
    # "#SEC_staff_reviews_in_past_5_year" : tt.INT,
    # "#SEC_staff_reviews_in_past_6_MO" : tt.INT,
    # "#SEC_staff_reviews_which_lasted_for_more_than_6_months_in_past_1_year" : tt.INT,
    # "#SEC_staff_reviews_which_lasted_for_more_than_6_months_in_past_2_years" : tt.INT,
    # "#SEC_staff_reviews_which_lasted_for_more_than_6_months_in_past_3_years" : tt.INT,
    # "#SEC_staff_reviews_which_lasted_for_more_than_6_months_in_past_4_years" : tt.INT,
    # "#SEC_staff_reviews_which_lasted_for_more_than_6_months_in_past_5_years" : tt.INT,
    # "#SEC_staff_reviews_currently_remaining_open" : tt.INT,
    # "#SEC_staff_reviews_currently_remaining_open_for_more_than_6_months" : tt.INT,
    # "#SEC_staff_reviews_raising_revenue_recognition_issue_in_past_1_year" : tt.INT,
    # "#SEC_staff_reviews_raising_revenue_recognition_issue_in_past_2_years" : tt.INT,
    # "#SEC_staff_reviews_raising_revenue_recognition_issue_in_past_3_years" : tt.INT,
    # "#SEC_staff_reviews_raising_revenue_recognition_issue_in_past_4_years" : tt.INT,
    # "#SEC_staff_reviews_raising_revenue_recognition_issue_in_past_5_years" : tt.INT,
    # "#SEC_staff_reviews_raising_revenue_recognition_issue_in_past_6_months" : tt.INT,
    # "#SEC_staff_reviews_raising_expense_recognition_issue_in_past_1_year" : tt.INT,
    # "#SEC_staff_reviews_raising_expense_recognition_issue_in_past_2_years" : tt.INT,
    # "#SEC_staff_reviews_raising_expense_recognition_issue_in_past_3_years" : tt.INT,
    # "#SEC_staff_reviews_raising_expense_recognition_issue_in_past_4_years" : tt.INT,
    # "#SEC_staff_reviews_raising_expense_recognition_issue_in_past_5_years" : tt.INT,
    # "#SEC_staff_reviews_raising_expense_recognition_issue_in_past_6_months" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_related_to_reserves_in_past_1_year" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_related_to_reserves_in_past_2_years" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_related_to_reserves_in_past_3_years" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_related_to_reserves_in_past_4_years" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_related_to_reserves_in_past_5_years" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_related_to_reserves_in_past_6_months" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_pertaining_to_Related_Party_Transactions_in_past_1_year" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_pertaining_to_Related_Party_Transactions_in_past_2_years" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_pertaining_to_Related_Party_Transactions_in_past_3_years" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_pertaining_to_Related_Party_Transactions_in_past_4_years" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_pertaining_to_Related_Party_Transactions_in_past_5_years" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_pertaining_to_Related_Party_Transactions_in_past_6_months" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_pertaining_to_asset_carrying_value,_impairment_or_write_down_in_past_1_year" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_pertaining_to_asset_carrying_value,_impairment_or_write_down_in_past_2_years" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_pertaining_to_asset_carrying_value,_impairment_or_write_down_in_past_3_years" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_pertaining_to_asset_carrying_value,_impairment_or_write_down_in_past_4_years" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_pertaining_to_asset_carrying_value,_impairment_or_write_down_in_past_5_years" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_pertaining_to_asset_carrying_value,_impairment_or_write_down_in_past_6_months" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_pertaining_to_executive_compensation_in_past_1_year" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_pertaining_to_executive_compensation_in_past_2_years" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_pertaining_to_executive_compensation_in_past_3_years" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_pertaining_to_executive_compensation_in_past_4_years" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_pertaining_to_executive_compensation_in_past_5_years" : tt.INT,
    # "#SEC_staff_reviews_raising_issues_pertaining_to_executive_compensation_in_past_6_months" : tt.INT,
    # "Each_common_equity_share_has_the_same_#votes_and_without_encumbrance" : tt.STRING,
    # "Voting_policy_and_director_resignation_policy_in_uncontested_elections" : tt.STRING,
    # "Supermajority_required_to_amend_charter_and_bylaws" : tt.STRING,
    # "Supermajority_required_to_approve_M&A_activities" : tt.STRING,
    # "Staggered_board" : tt.STRING,
    # "Shareholder_rights_plan_approved_by_shareholders" : tt.STRING,
    # "Shareholder_rights_plan_trigger:_ownership_percentage" : tt.STRING,
    # "Shareholder_rights_plan_has_qualified_offer_provision" : tt.STRING,
    # "Shareholder_Rights_Plan_-_Expiry_in_years" : tt.STRING,
    # "Shareholder_rights_plan_-_since_effectuated_or_last_reintroduced_in_years" : tt.STRING,
    # "Board_authorized_to_issue_blank_check_preferred_stock_without_shareholders_approval" : tt.STRING,
    # "Convening_Special_Meeting_-_Ownership_percentage_requirement" : tt.STRING,
    # "Shareholders_can_act_through_written_consent" : tt.STRING,
    # "#times_listing_standards_were_violated_or_notice_of_delisting_served_in_past_1_year" : tt.INT,
    # "#times_listing_standards_were_violated_or_notice_of_delisting_served_in_past_2_years" : tt.INT,
    # "#times_listing_standards_were_violated_or_notice_of_delisting_served_in_past_3_years" : tt.INT,
    # "#times_listing_standards_were_violated_or_notice_of_delisting_served_in_past_4_years" : tt.INT,
    # "#times_listing_standards_were_violated_or_notice_of_delisting_served_in_past_5_years" : tt.INT,
    # "#times_listing_standards_were_violated_or_notice_of_delisting_served_in_past_6_months" : tt.INT,
    # "#instances_of_suspension_of_trading_in_past_1_year" : tt.INT,
    # "#instances_of_suspension_of_trading_in_past_2_years" : tt.INT,
    # "#instances_of_suspension_of_trading_in_past_3_years" : tt.INT,
    # "#instances_of_suspension_of_trading_in_past_4_years" : tt.INT,
    # "#instances_of_suspension_of_trading_in_past_5_years" : tt.INT,
    # "#instances_of_suspension_of_trading_in_past_6m" : tt.INT,
    # "CEO_holds_Board_Chair" : tt.STRING,
    # "%_independent_directors" : tt.STRING,
    # "%_independent_audit_committee_members" : tt.STRING,
    # "%_independent_compensation_committee_members" : tt.STRING,
    # "%_independent_nominating_committee_members" : tt.STRING,
    # "%_directors_on_4_or_more_(other)_public_company_boards_on_last_reported_proxy_record_date" : tt.STRING,
    # "#other_public_company_boards_the_CEO_serves_on_last_reported_proxy_record_date" : tt.STRING,
    # "%_meetings_directors_attended_in_a_year_>=75%_as_reported_on_last_proxy_statement" : tt.STRING,
    # "If_there_are_disclosed_governance_guidelines" : tt.STRING,
    # "If_Non-executive_directors_met_without_the_presence_of_executive_members_(executive_sessions)_at_least_once_in_a_year,_as_reported_on_last_proxy_statement" : tt.STRING,
    # "#related_party_transactions_involving_board_chair_and_or_CEO_in_past_1_year" : tt.INT,
    # "#related_party_transactions_involving_board_chair_and_or_CEO_in_past_2_years" : tt.INT,
    # "#related_party_transactions_involving_board_chair_and_or_CEO_in_past_3_years" : tt.INT,
    # "#related_party_transactions_involving_board_chair_and_or_CEO_in_past_4_years" : tt.INT,
    # "#related_party_transactions_involving_board_chair_and_or_CEO_in_past_5_years" : tt.INT,
    "#board_chair_departures_in_past_1_year": tt.INT,
    # "#board_chair_departures_in_past_2_years" : tt.INT,
    # "#board_chair_departures_in_past_3_years" : tt.INT,
    # "#board_chair_departures_in_past_4_years" : tt.INT,
    # "#board_chair_departures_in_past_5_years" : tt.INT,
    # "#board_chair_departures_in_past_6_months" : tt.INT,
    "#audit_committee_chair_departures_in_past_1_year": tt.INT,
    # "#audit_committee_chair_departures_in_past_2_years" : tt.INT,
    # "#audit_committee_chair_departures_in_past_3_years" : tt.INT,
    # "#audit_committee_chair_departures_in_past_4_years" : tt.INT,
    # "#audit_committee_chair_departures_in_past_5_years" : tt.INT,
    # "#audit_committee_chair_departures_in_past_6_months" : tt.INT,
    "#compensation_committee_chair_departures_in_past_1_year": tt.INT,
    # "#compensation_committee_chair_departures_in_past_2_years" : tt.INT,
    # "#compensation_committee_chair_departures_in_past_3_years" : tt.INT,
    # "#compensation_committee_chair_departures_in_past_4_years" : tt.INT,
    # "#compensation_committee_chair_departures_in_past_5_years" : tt.INT,
    # "#compensation_committee_chair_departures_in_past_6_months" : tt.INT,
    "#nominating_committee_chair_departures_in_past_1_year": tt.INT,
    # "#nominating_committee_chair_departures_in_past_2_years" : tt.INT,
    # "#nominating_committee_chair_departures_in_past_3_years" : tt.INT,
    # "#nominating_committee_chair_departures_in_past_4_years" : tt.INT,
    # "#nominating_committee_chair_departures_in_past_5_years" : tt.INT,
    # "#nominating_committee_chair_departures_in_past_6_months" : tt.INT,
    "#board_departures_in_past_1_year": tt.INT,
    # "#board_departures_in_past_2_years" : tt.INT,
    # "#board_departures_in_past_3_years" : tt.INT,
    # "#board_departures_in_past_4_years" : tt.INT,
    # "#board_departures_in_past_5_years" : tt.INT,
    # "#board_departures_in_past_6_months" : tt.INT,
    "#audit_committee_departures_in_past_1_year": tt.INT,
    # "#audit_committee_departures_in_past_2_years" : tt.INT,
    # "#audit_committee_departures_in_past_3_years" : tt.INT,
    # "#audit_committee_departures_in_past_4_years" : tt.INT,
    # "#audit_committee_departures_in_past_5_years" : tt.INT,
    # "#audit_committee_departures_in_past_6_months" : tt.INT,
    "#compensation_committee_departures_in_past_1_year": tt.INT,
    # "#compensation_committee_departures_in_past_2_years" : tt.INT,
    # "#compensation_committee_departures_in_past_3_years" : tt.INT,
    # "#compensation_committee_departures_in_past_4_years" : tt.INT,
    # "#compensation_committee_departures_in_past_5_years" : tt.INT,
    # "#compensation_committee_departures_in_past_6_months" : tt.INT,
    "#nominating_committee_departures_in_past_1_year": tt.INT,
    # "#nominating_committee_departures_in_past_2_years" : tt.INT,
    # "#nominating_committee_departures_in_past_3_years" : tt.INT,
    # "#nominating_committee_departures_in_past_4_years" : tt.INT,
    # "#nominating_committee_departures_in_past_5_years" : tt.INT,
    # "#nominating_committee_departures_in_past_6_months" : tt.INT,
    # "Pay_performance_alignment:_1-year_annualized_CEO_compensation_versus_1-year_TSR_(total_shareholder_return)_in_peer_group" : tt.STRING,
    # "Pay_performance_alignment:_1-year_top_5_NEO_(named_executive_officers)_aggregate_compensation_versus_1-year_TSR_in_peer_group" : tt.STRING,
    # "Pay_performance_alignment:_1-year_annualized_CEO_compensation_versus_1-year_annual_ROTC_(return_on_total_capital)_in_peer_group" : tt.STRING,
    # "Pay_performance_alignment:_1-year_top_5_NEO_aggregate_compensation_versus_1-year_annual_ROTC_in_peer_group" : tt.STRING,
    # "Pay_performance_alignment:_2-year_average_annualized_CEO_compensation_versus_2-year_compounded_annualized_TSR_in_peer_group" : tt.STRING,
    # "Pay_performance_alignment:_2-year_average_annual_top_5_NEO_aggregate_compensation_versus_2-_year_compounded_annualized_TSR_in_peer_group" : tt.STRING,
    # "Pay_performance_alignment:_2-year_average_annualized_CEO_compensation_versus_2-year_average_annual_ROTC_in_peer_group" : tt.STRING,
    # "Pay_performance_alignment:_2-year_average_annual_top_5_NEO_aggregate_compensation_versus_2-year_average_annual_ROTC_in_peer_group" : tt.STRING,
    # "Pay_performance_alignment:_3-year_average_annualized_CEO_compensation_versus_3-year_compounded_annualized_TSR_in_peer_group" : tt.STRING,
    # "Pay_performance_alignment:_3-year_average_annual_top_5_NEO_aggregate_compensation_versus_3-year_compounded_annualized_TSR_in_peer_group" : tt.STRING,
    # "Pay_performance_alignment:_3-year_average_annualized_CEO_compensation_versus_3-year_average_annual_ROTC_in_peer_group" : tt.STRING,
    # "Pay_performance_alignment:_3-year_average_annual_top_5_NEO_aggregate_compensation_versus_3-year_average_annual_ROTC_in_peer_group" : tt.STRING,
    # "Pay_performance_alignment:_4-year_average_annualized_CEO_compensation_versus_4-year_compounded_annualized_TSR_in_peer_group" : tt.STRING,
    # "Pay_performance_alignment:_4-year_average_annual_top_5_NEO_aggregate_compensation_versus_4-year_compounded_annualized_TSR_in_peer_group" : tt.STRING,
    # "Pay_performance_alignment:_4-year_average_annualized_CEO_compensation_versus_4-year_average_annual_ROTC_in_peer_group" : tt.STRING,
    # "Pay_performance_alignment:_4-year_average_annual_top_5_NEO_aggregate_compensation_versus_4-year_average_annual_ROTC_in_peer_group" : tt.STRING,
    # "Pay_performance_alignment:_5-year_average_annualized_CEO_compensation_versus_5-year_compounded_annualized_TSR_in_peer_group" : tt.STRING,
    # "Pay_performance_alignment:_5-year_average_annual_top_5_NEO_aggregate_compensation_versus_5-year_compounded_annualized_TSR_in_peer_group" : tt.STRING,
    # "Pay_performance_alignment:_5-year_average_annualized_CEO_compensation_versus_5-year_average_annual_ROTC_in_peer_group" : tt.STRING,
    # "Pay_performance_alignment:_5-year_average_annual_top_5_NEO_aggregate_compensation_versus_5-year_average_annual_ROTC_in_peer_group" : tt.STRING,
    # "If_shareholders_have_Say_on_Pay" : tt.STRING,
    # "If_there_is_disclosed_compensation_claw_back_provision" : tt.STRING,
    "#CEO_departures_in_past_1_year": tt.INT,
    # "#CEO_departures_in_past_2_years" : tt.INT,
    # "#CEO_departures_in_past_3_years" : tt.INT,
    # "#CEO_departures_in_past_4_years" : tt.INT,
    # "#CEO_departures_in_past_5_years" : tt.INT,
    # "#CEO_departures_in_past_6_months" : tt.INT,
    "#CFO_departures_in_past_1_year": tt.INT,
    # "#CFO_departures_in_past_2_years" : tt.INT,
    # "#CFO_departures_in_past_3_years" : tt.INT,
    # "#CFO_departures_in_past_4_years" : tt.INT,
    # "#CFO_departures_in_past_5_years" : tt.INT,
    # "#CFO_departures_in_past_6_months" : tt.INT,
    "#CAO_departures_in_past_1_year": tt.INT,
    # "#CAO_departures_in_past_2_years" : tt.INT,
    # "#CAO_departures_in_past_3_years" : tt.INT,
    # "#CAO_departures_in_past_4_years" : tt.INT,
    # "#CAO_departures_in_past_5_years" : tt.INT,
    # "#CAO_departures_in_past_6_months" : tt.INT,
    "#General_Counsel_departures_in_past_1_year": tt.INT,
    # "#General_Counsel_departures_in_past_2_years" : tt.INT,
    # "#General_Counsel_departures_in_past_3_years" : tt.INT,
    # "#General_Counsel_departures_in_past_4_years" : tt.INT,
    # "#General_Counsel_departures_in_past_5_years" : tt.INT,
    # "#General_Counsel_departures_in_past_6_months" : tt.INT,
    "#COO_departures_in_past_1_year": tt.INT,
    # "#COO_departures_in_past_2_years" : tt.INT,
    # "#COO_departures_in_past_3_years" : tt.INT,
    # "#COO_departures_in_past_4_years" : tt.INT,
    # "#COO_departures_in_past_5_years" : tt.INT,
    # "#COO_departures_in_past_6_months" : tt.INT,
    "#CPO_departures_in_past_1_year": tt.INT,
    # "#CPO_departures_in_past_2_years" : tt.INT,
    # "#CPO_departures_in_past_3_years" : tt.INT,
    # "#CPO_departures_in_past_4_years" : tt.INT,
    # "#CPO_departures_in_past_5_years" : tt.INT,
    # "#CPO_departures_in_past_6_months" : tt.INT,
    # "#EPA_or_other_regulator_environmental_investigations_in_past_1_year" : tt.INT,
    # "#EPA_or_other_regulator_environmental_investigations_in_past_2_years" : tt.INT,
    # "#EPA_or_other_regulator_environmental_investigations_in_past_3_years" : tt.INT,
    # "#EPA_or_other_regulator_environmental_investigations_in_past_4_years" : tt.INT,
    # "#EPA_or_other_regulator_environmental_investigations_in_past_5_years" : tt.INT,
    # "#EPA_or_other_regulator_environmental_investigations_in_past_6_months" : tt.INT,
    # "#EPA_or_other_regulator_environmental_investigations_currently_remaining_open" : tt.INT,
    # "#regulator_or_board_investigations_on_labor_law_violation_at_workplace_including_within_third-party_supply_chain,_in_past_1_year" : tt.INT,
    # "#regulator_or_board_investigations_on_labor_law_violation_at_workplace_including_within_third-party_supply_chain,_in_past_2_years" : tt.INT,
    # "#regulator_or_board_investigations_on_labor_law_violation_at_workplace_including_within_third-party_supply_chain,_in_past_3_years" : tt.INT,
    # "#regulator_or_board_investigations_on_labor_law_violation_at_workplace_including_within_third-party_supply_chain,_in_past_4_years" : tt.INT,
    # "#regulator_or_board_investigations_on_labor_law_violation_at_workplace_including_within_third-party_supply_chain,_in_past_5_years" : tt.INT,
    # "#regulator_or_board_investigations_on_labor_law_violation_at_workplace_including_within_third-party_supply_chain,_in_past_6_months" : tt.INT,
    # "#regulator_or_board_investigations_on_labor_law_violation_at_workplace_including_within_third-party_supply_chain,_currently_remaining_open" : tt.INT,
    # "Gender_diversity_in_board_-_percentage_of_women" : tt.FLOAT,
    # "Gender_diversity_in_executive_suite_-_percentage_of_women" : tt.FLOAT,
    # "GRI_(Global_Reporting_Initiative)_reporting:_Application_level" : tt.STRING,
    # "GRI_reporting_-_#sustainability_guidelines_referenced" : tt.STRING,
}
