name: Release

on:
  pull_request:

jobs:
  test-notebooks:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 1) Check out your repo
      - uses: actions/checkout@v4

      # 2) Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3) Install your Python deps + Playwright browsers + system libs
      - name: Install dependencies
        run: |
          pip install uv
          uv sync     
          uv run playwright install-deps
          uv run playwright install

      # 4) Launch JupyterLab in the background
      - name: Start JupyterLab
        run: |
          nohup uv run jupyter-lab \
            --no-browser \
            --ip=0.0.0.0 \
            --port=8888 \
            --NotebookApp.token='' \
            --NotebookApp.password='' \
          > jupyter.log 2>&1 &
          echo $! > jupyter.pid

          # wait until JupyterLab is listening
          echo "⏳ Waiting for JupyterLab…"
          for i in {1..60}; do
            if curl --silent --fail http://localhost:8888/lab ; then
              echo "✅ JupyterLab is up!"
              break
            fi
            sleep 1
          done

      # 5) Run your notebook‐testing script (Playwright, pytest+nbmake, etc.)
      - name: Run web render tests
        env:
          PLAYWRIGHT_HEADLESS: "1"
        run: |
          make web-render

      # 6) Always tear down JupyterLab when we're done
      - name: Stop JupyterLab
        if: always()
        run: |
          kill $(cat jupyter.pid) || true
