name: Release

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  render-notebooks:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 1) Check out your repo
      - uses: actions/checkout@v4

      # 2) Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3) Install your Python deps + Playwright browsers + system libs
      - name: Install dependencies
        run: |
          pip install uv
          uv sync     

      # 4) Run your notebook‐testing script (Playwright, pytest+nbmake, etc.)
      - name: Run web render tests
        env:
          PLAYWRIGHT_HEADLESS: "1"
        run: |
          make web-render
